name: ADElevate
 
on:
  push:
    branches: ["main"]
 
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}

    steps:
      - name: Debug Environment
        run: |
          echo "HF_TOKEN is set? -> ${HF_TOKEN:+yes}"
          echo "TOGETHER_API_KEY is set? -> ${TOGETHER_API_KEY:+yes}"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f req_prod.txt ]; then pip install -r req_prod.txt; fi

      - name: Lint with flake8 and PyTest
        run: |
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Docker Build and Push to Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: chaita13/adelevate
          
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        

           